#name, main, version and api are required
name: RTools
main: RTools\MainClass
version: 0.0.1A
api: [3.0.0-ALPHA11]

load: POSTWORLD
author: Jackthehack21
description: General Commands
website: https://github.com/Jackthehaxk21/Example-Plugin
commands:
 ping:
  description: "Ping the RTools Plugin"
  usage: "/ping"
  permission: RTools.ping