#name, main, version and api are required
name: Jacks Plugin
main: ExamplePlugin\MainClass
version: 0.01
api: [3.0.0-ALPHA11]

load: POSTWORLD
author: Jackthehaxk21
description: Example plugin showing my abilites
website: https://github.com/PocketMine/ExamplePlugin
